import Head from "next/head"
import Link from 'next/link'

import Banner from '../../components/banner/banner.jsx'


import styles from '../../styles/Home.module.scss'


import {useRouter} from "next/router"

const Dinamic = () => {
  const router = useRouter().query.id
  const textFrase = `${router} faz bem para a saúde`
  return (
    <div>
      <Head>
        <title>{router}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/'> 
        <a>back to home</a>
        </Link>
        <Banner title1={router} title2='com queijo' textButton='voltarzar' text={textFrase}/>
      </main>
    </div>
  )
}

export default Dinamic