import Head from 'next/head'
import Banner from '../components/banner/banner.jsx'
import Card from '../components/card/card.jsx'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Batata Assada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Banner title1='Batata' title2='assada' textButton='clica não' text='sua batata está assando'/>        <Card alt='card' imgUrl='/static/back.png' href='dinamic/macarrão' name='macarrão'>
          vocês são legais
        </Card>
      </main>
    </div>
  )
}
