import Head from 'next/head'

import Banner from '../components/banner/banner.jsx'
import Card from '../components/card/card.jsx'

import styles from '../styles/Home.module.scss'

import coffeeData from '../data/coffee.json'

export async function getStaticProps(context) {
  return {
    props: {
      coffeeData,
    },
  }
}

export default function Home(props) {

  const title = props.coffeeData.texts.title
  let [title1, title2] = title.split('-')

  return (

    <div className={styles.container}>
      <Head>
        <title>{props.coffeeData.texts.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner title1={title1} title2={title2} textButton='clica não!' text={props.coffeeData.texts.subtitle}/>        
        {props.coffeeData.personas.length > 0 && (
          <>
            <h2>Showcase</h2>
            <div className={styles.showcase}>
              {props.coffeeData.personas.map((coff) => {
                return (
                  <div className={styles.showcaseItem} key={coff.id}>
                    <Card
                      name={coff.name}
                      imgUrl={coff.imgUrl}
                      href={`/dinamic/${coff.name}`}
                    />
                  </div>
                )
              })}
            </div>
          </>
        )}

      </main>
      <footer>

      </footer>
    </div>
  )
}
