import Head from 'next/head'
import Banner from '../components/banner/banner.jsx'
import Card from '../components/card/card.jsx'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Batata Assada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner title1='Batata' title2='assada' textButton='clica não' text='sua batata está assando'/>        
      </main>
      <div className={styles.cards}>
        <Card href='./dinamic/Pimentel' text1='Pimentel foi à feira,' text2='não tinha o que comprar' name='Card 1'/>
        <Card href='./dinamic/Dudu' text1='Comprou uma cadeira' text2='pro Dudu se sentar' name='Card 2'/>
      </div>
    </div>
  )
}
